// Biblical Hebrew Word of the Day — word bank.
// Each entry: hebrew, translit (academic), pron (plain-English),
// pos (part of speech), gloss (short), meaning (fuller note),
// strongs, occurrences (approx. count in the Hebrew Bible),
// and a sample verse {ref, he, en} with the word in context.
//
// Vowel-pointed Hebrew is provided for each headword. Verse snippets are
// kept short and drawn from well-known passages.

const WORDS = [
  {
    hebrew: "בְּרֵאשִׁית",
    translit: "bərēʾšîṯ",
    pron: "be-ray-SHEET",
    pos: "noun (f.)",
    gloss: "in the beginning",
    meaning:
      "From רֹאשׁ (rosh, “head”). The first word of the Bible: “in the beginning,” the start or first/best of something.",
    strongs: "H7225",
    occurrences: 51,
    verse: {
      ref: "Genesis 1:1",
      he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים",
      en: "In the beginning God created…",
    },
  },
  {
    hebrew: "אֱלֹהִים",
    translit: "ʾĕlōhîm",
    pron: "eh-lo-HEEM",
    pos: "noun (m. pl.)",
    gloss: "God; gods",
    meaning:
      "Plural in form but usually singular in sense when referring to the God of Israel — a plural of majesty.",
    strongs: "H430",
    occurrences: 2600,
    verse: {
      ref: "Genesis 1:1",
      he: "בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם",
      en: "God created the heavens…",
    },
  },
  {
    hebrew: "יְהוָה",
    translit: "YHWH",
    pron: "Adonai (read aloud)",
    pos: "proper noun",
    gloss: "the LORD",
    meaning:
      "The personal covenant name of God (the Tetragrammaton), linked to the verb “to be.” Traditionally read aloud as Adonai.",
    strongs: "H3068",
    occurrences: 6828,
    verse: {
      ref: "Exodus 3:15",
      he: "יְהוָה אֱלֹהֵי אֲבֹתֵיכֶם",
      en: "the LORD, the God of your fathers…",
    },
  },
  {
    hebrew: "שָׁלוֹם",
    translit: "šālôm",
    pron: "sha-LOME",
    pos: "noun (m.)",
    gloss: "peace, wholeness",
    meaning:
      "Far more than the absence of conflict — completeness, welfare, health, and harmony. Used as a greeting and farewell.",
    strongs: "H7965",
    occurrences: 237,
    verse: {
      ref: "Numbers 6:26",
      he: "וְיָשֵׂם לְךָ שָׁלוֹם",
      en: "…and give you peace.",
    },
  },
  {
    hebrew: "חֶסֶד",
    translit: "ḥeseḏ",
    pron: "KHEH-sed",
    pos: "noun (m.)",
    gloss: "steadfast love",
    meaning:
      "Loyal, covenant love and kindness — mercy that keeps faith. A central term for God’s character.",
    strongs: "H2617",
    occurrences: 248,
    verse: {
      ref: "Psalm 136:1",
      he: "כִּי לְעוֹלָם חַסְדּוֹ",
      en: "…for his steadfast love endures forever.",
    },
  },
  {
    hebrew: "רוּחַ",
    translit: "rûaḥ",
    pron: "ROO-akh",
    pos: "noun (f.)",
    gloss: "spirit, wind, breath",
    meaning:
      "Breath, wind, or spirit — the animating force; also the Spirit of God moving in the world.",
    strongs: "H7307",
    occurrences: 378,
    verse: {
      ref: "Genesis 1:2",
      he: "וְרוּחַ אֱלֹהִים מְרַחֶפֶת",
      en: "…and the Spirit of God was hovering…",
    },
  },
  {
    hebrew: "דָּבָר",
    translit: "dāḇār",
    pron: "da-VAR",
    pos: "noun (m.)",
    gloss: "word, thing, matter",
    meaning:
      "Both a spoken “word” and the “thing” it brings about — speech and event are bound together.",
    strongs: "H1697",
    occurrences: 1454,
    verse: {
      ref: "Psalm 119:105",
      he: "נֵר לְרַגְלִי דְבָרֶךָ",
      en: "Your word is a lamp to my feet…",
    },
  },
  {
    hebrew: "תּוֹרָה",
    translit: "tôrāh",
    pron: "toe-RAH",
    pos: "noun (f.)",
    gloss: "instruction, law",
    meaning:
      "Teaching or instruction (from a root “to throw/point the way”), and so the Law — the first five books.",
    strongs: "H8451",
    occurrences: 219,
    verse: {
      ref: "Psalm 1:2",
      he: "וּבְתוֹרָתוֹ יֶהְגֶּה",
      en: "…and on his law he meditates.",
    },
  },
  {
    hebrew: "נֶפֶשׁ",
    translit: "nep̄eš",
    pron: "NEH-fesh",
    pos: "noun (f.)",
    gloss: "soul, life, self",
    meaning:
      "The living self — life, breath, appetite, the whole person. Not a “soul” separate from the body.",
    strongs: "H5315",
    occurrences: 757,
    verse: {
      ref: "Deuteronomy 6:5",
      he: "וּבְכָל־נַפְשְׁךָ",
      en: "…and with all your soul…",
    },
  },
  {
    hebrew: "אֱמֶת",
    translit: "ʾĕmeṯ",
    pron: "eh-MET",
    pos: "noun (f.)",
    gloss: "truth, faithfulness",
    meaning:
      "Truth as firmness and reliability — what is dependable and stands the test, not merely factual accuracy.",
    strongs: "H571",
    occurrences: 127,
    verse: {
      ref: "Psalm 25:5",
      he: "הַדְרִיכֵנִי בַאֲמִתֶּךָ",
      en: "Lead me in your truth…",
    },
  },
  {
    hebrew: "צֶדֶק",
    translit: "ṣeḏeq",
    pron: "TSEH-dek",
    pos: "noun (m.)",
    gloss: "righteousness, justice",
    meaning:
      "Rightness — conformity to a moral and relational standard; doing right by God and neighbor.",
    strongs: "H6664",
    occurrences: 119,
    verse: {
      ref: "Psalm 85:10",
      he: "צֶדֶק וְשָׁלוֹם נָשָׁקוּ",
      en: "Righteousness and peace kiss…",
    },
  },
  {
    hebrew: "קָדוֹשׁ",
    translit: "qāḏôš",
    pron: "ka-DOSH",
    pos: "adjective",
    gloss: "holy, set apart",
    meaning:
      "Holy — set apart, distinct, sacred. Used supremely of God, who is wholly other.",
    strongs: "H6918",
    occurrences: 116,
    verse: {
      ref: "Isaiah 6:3",
      he: "קָדוֹשׁ קָדוֹשׁ קָדוֹשׁ",
      en: "Holy, holy, holy…",
    },
  },
  {
    hebrew: "לֵב",
    translit: "lēḇ",
    pron: "LEV",
    pos: "noun (m.)",
    gloss: "heart, mind, will",
    meaning:
      "The inner person — the seat of thought, will, and emotion. In Hebrew thinking happens in the heart.",
    strongs: "H3820",
    occurrences: 598,
    verse: {
      ref: "Proverbs 3:5",
      he: "בְּטַח אֶל־יְהוָה בְּכָל־לִבֶּךָ",
      en: "Trust in the LORD with all your heart…",
    },
  },
  {
    hebrew: "אוֹר",
    translit: "ʾôr",
    pron: "ORE",
    pos: "noun (m.)",
    gloss: "light",
    meaning:
      "Light — physical light, and figuratively life, guidance, and the favor of God.",
    strongs: "H216",
    occurrences: 122,
    verse: {
      ref: "Genesis 1:3",
      he: "יְהִי אוֹר וַיְהִי־אוֹר",
      en: "“Let there be light,” and there was light.",
    },
  },
  {
    hebrew: "בְּרִית",
    translit: "bərîṯ",
    pron: "be-REET",
    pos: "noun (f.)",
    gloss: "covenant",
    meaning:
      "A binding agreement or covenant, often sealed with an oath — the framework of God’s relationship with his people.",
    strongs: "H1285",
    occurrences: 287,
    verse: {
      ref: "Genesis 9:13",
      he: "לְאוֹת בְּרִית",
      en: "…a sign of the covenant.",
    },
  },
  {
    hebrew: "כָּבוֹד",
    translit: "kāḇôḏ",
    pron: "ka-VODE",
    pos: "noun (m.)",
    gloss: "glory, honor, weight",
    meaning:
      "From a root meaning “heavy” — weightiness, hence honor, splendor, and the visible glory of God.",
    strongs: "H3519",
    occurrences: 200,
    verse: {
      ref: "Psalm 19:1",
      he: "מְסַפְּרִים כְּבוֹד־אֵל",
      en: "…declare the glory of God.",
    },
  },
  {
    hebrew: "עוֹלָם",
    translit: "ʿôlām",
    pron: "oh-LAHM",
    pos: "noun (m.)",
    gloss: "forever, eternity",
    meaning:
      "Long, distant, or unending time — antiquity or perpetuity; “forever,” the age beyond sight.",
    strongs: "H5769",
    occurrences: 439,
    verse: {
      ref: "Psalm 90:2",
      he: "מֵעוֹלָם עַד־עוֹלָם",
      en: "…from everlasting to everlasting.",
    },
  },
  {
    hebrew: "חָכְמָה",
    translit: "ḥoḵmāh",
    pron: "khokh-MAH",
    pos: "noun (f.)",
    gloss: "wisdom, skill",
    meaning:
      "Practical skill for living well — insight, craft, and the art of righteous, godly living.",
    strongs: "H2451",
    occurrences: 149,
    verse: {
      ref: "Proverbs 9:10",
      he: "תְּחִלַּת חָכְמָה יִרְאַת יְהוָה",
      en: "The fear of the LORD is the beginning of wisdom.",
    },
  },
  {
    hebrew: "יִרְאָה",
    translit: "yirʾāh",
    pron: "yir-AH",
    pos: "noun (f.)",
    gloss: "fear, reverence",
    meaning:
      "Fear — but also awe and reverence; the right response of a creature before the holy God.",
    strongs: "H3374",
    occurrences: 45,
    verse: {
      ref: "Psalm 111:10",
      he: "רֵאשִׁית חָכְמָה יִרְאַת יְהוָה",
      en: "The fear of the LORD is the beginning of wisdom.",
    },
  },
  {
    hebrew: "אֶרֶץ",
    translit: "ʾereṣ",
    pron: "EH-rets",
    pos: "noun (f.)",
    gloss: "land, earth",
    meaning:
      "The earth, a land, or the ground — both the whole world and a particular territory.",
    strongs: "H776",
    occurrences: 2504,
    verse: {
      ref: "Genesis 1:1",
      he: "וְאֵת הָאָרֶץ",
      en: "…and the earth.",
    },
  },
  {
    hebrew: "שָׁמַיִם",
    translit: "šāmayim",
    pron: "sha-MA-yim",
    pos: "noun (m. pl.)",
    gloss: "heavens, sky",
    meaning:
      "The heavens or sky — the dual/plural form spanning the visible sky and the dwelling of God.",
    strongs: "H8064",
    occurrences: 421,
    verse: {
      ref: "Psalm 19:1",
      he: "הַשָּׁמַיִם מְסַפְּרִים",
      en: "The heavens declare…",
    },
  },
  {
    hebrew: "מַיִם",
    translit: "mayim",
    pron: "MA-yim",
    pos: "noun (m. pl.)",
    gloss: "water, waters",
    meaning:
      "Water — always plural in form; the deep, the seas, rain, and life-giving streams.",
    strongs: "H4325",
    occurrences: 580,
    verse: {
      ref: "Genesis 1:2",
      he: "עַל־פְּנֵי הַמָּיִם",
      en: "…over the face of the waters.",
    },
  },
  {
    hebrew: "אָדָם",
    translit: "ʾāḏām",
    pron: "ah-DAHM",
    pos: "noun (m.)",
    gloss: "man, humankind",
    meaning:
      "Humanity, a human being, or the name Adam — wordplay with אֲדָמָה (adamah, “ground”).",
    strongs: "H120",
    occurrences: 554,
    verse: {
      ref: "Genesis 2:7",
      he: "וַיִּיצֶר יְהוָה אֱלֹהִים אֶת־הָאָדָם",
      en: "The LORD God formed the man…",
    },
  },
  {
    hebrew: "עַם",
    translit: "ʿam",
    pron: "AHM",
    pos: "noun (m.)",
    gloss: "people, nation",
    meaning:
      "A people bound by kinship and covenant — especially Israel as the people of God.",
    strongs: "H5971",
    occurrences: 1869,
    verse: {
      ref: "Ruth 1:16",
      he: "עַמֵּךְ עַמִּי",
      en: "Your people shall be my people…",
    },
  },
  {
    hebrew: "יָד",
    translit: "yāḏ",
    pron: "YAHD",
    pos: "noun (f.)",
    gloss: "hand, power",
    meaning:
      "The hand — and so strength, power, agency, or control (“by the hand of…”).",
    strongs: "H3027",
    occurrences: 1627,
    verse: {
      ref: "Psalm 31:5",
      he: "בְּיָדְךָ אַפְקִיד רוּחִי",
      en: "Into your hand I commit my spirit.",
    },
  },
  {
    hebrew: "פָּנִים",
    translit: "pānîm",
    pron: "pa-NEEM",
    pos: "noun (m. pl.)",
    gloss: "face, presence",
    meaning:
      "Face — always plural; figuratively one’s presence, favor, or person (“before the face of”).",
    strongs: "H6440",
    occurrences: 2126,
    verse: {
      ref: "Numbers 6:25",
      he: "יָאֵר יְהוָה פָּנָיו אֵלֶיךָ",
      en: "The LORD make his face shine on you…",
    },
  },
  {
    hebrew: "שֵׁם",
    translit: "šēm",
    pron: "SHAME",
    pos: "noun (m.)",
    gloss: "name, reputation",
    meaning:
      "A name — and with it identity, character, and reputation. To act “in the name” is to act with authority.",
    strongs: "H8034",
    occurrences: 864,
    verse: {
      ref: "Psalm 113:3",
      he: "מְהֻלָּל שֵׁם יְהוָה",
      en: "…the name of the LORD is to be praised.",
    },
  },
  {
    hebrew: "בַּיִת",
    translit: "bayiṯ",
    pron: "BA-yit",
    pos: "noun (m.)",
    gloss: "house, household",
    meaning:
      "A house or dwelling — also a household, family, or dynasty; the Temple is the “house” of God.",
    strongs: "H1004",
    occurrences: 2055,
    verse: {
      ref: "Joshua 24:15",
      he: "אֲנִי וּבֵיתִי נַעֲבֹד אֶת־יְהוָה",
      en: "…as for me and my house, we will serve the LORD.",
    },
  },
  {
    hebrew: "מֶלֶךְ",
    translit: "meleḵ",
    pron: "MEH-lekh",
    pos: "noun (m.)",
    gloss: "king",
    meaning:
      "A king or sovereign — human rulers, and the LORD as King over all.",
    strongs: "H4428",
    occurrences: 2530,
    verse: {
      ref: "Psalm 47:7",
      he: "מֶלֶךְ כָּל־הָאָרֶץ אֱלֹהִים",
      en: "God is the King of all the earth.",
    },
  },
  {
    hebrew: "מִשְׁפָּט",
    translit: "mišpāṭ",
    pron: "mish-PAHT",
    pos: "noun (m.)",
    gloss: "justice, judgment",
    meaning:
      "Justice and just judgment — a legal decision, a right, or the ordinance that secures fairness.",
    strongs: "H4941",
    occurrences: 421,
    verse: {
      ref: "Micah 6:8",
      he: "עֲשׂוֹת מִשְׁפָּט",
      en: "…to do justice…",
    },
  },
  {
    hebrew: "עֶבֶד",
    translit: "ʿeḇeḏ",
    pron: "EH-ved",
    pos: "noun (m.)",
    gloss: "servant, slave",
    meaning:
      "A servant or slave — also a title of honor: “servant of the LORD.”",
    strongs: "H5650",
    occurrences: 800,
    verse: {
      ref: "Isaiah 42:1",
      he: "הֵן עַבְדִּי",
      en: "Behold my servant…",
    },
  },
  {
    hebrew: "נָבִיא",
    translit: "nāḇîʾ",
    pron: "na-VEE",
    pos: "noun (m.)",
    gloss: "prophet",
    meaning:
      "A prophet — one called to speak for God, a spokesman bearing the divine word.",
    strongs: "H5030",
    occurrences: 317,
    verse: {
      ref: "Deuteronomy 18:15",
      he: "נָבִיא מִקִּרְבְּךָ",
      en: "…a prophet from among you…",
    },
  },
  {
    hebrew: "כֹּהֵן",
    translit: "kōhēn",
    pron: "ko-HANE",
    pos: "noun (m.)",
    gloss: "priest",
    meaning:
      "A priest — one who mediates between God and people, offering sacrifice and blessing.",
    strongs: "H3548",
    occurrences: 750,
    verse: {
      ref: "Exodus 19:6",
      he: "מַמְלֶכֶת כֹּהֲנִים",
      en: "…a kingdom of priests…",
    },
  },
  {
    hebrew: "חַיִּים",
    translit: "ḥayyîm",
    pron: "kha-YEEM",
    pos: "noun (m. pl.)",
    gloss: "life",
    meaning:
      "Life — plural in form, expressing fullness; living, lifetime, and flourishing.",
    strongs: "H2416",
    occurrences: 148,
    verse: {
      ref: "Psalm 16:11",
      he: "אֹרַח חַיִּים",
      en: "…the path of life.",
    },
  },
  {
    hebrew: "אַהֲבָה",
    translit: "ʾahăḇāh",
    pron: "a-ha-VAH",
    pos: "noun (f.)",
    gloss: "love",
    meaning:
      "Love — devotion and affection between people, and the love of God for his people.",
    strongs: "H160",
    occurrences: 40,
    verse: {
      ref: "Song of Songs 8:7",
      he: "מַיִם רַבִּים לֹא יוּכְלוּ לְכַבּוֹת אֶת־הָאַהֲבָה",
      en: "Many waters cannot quench love.",
    },
  },
  {
    hebrew: "אָמַר",
    translit: "ʾāmar",
    pron: "ah-MAR",
    pos: "verb",
    gloss: "to say, speak",
    meaning:
      "The common verb “to say” — introducing speech throughout the narrative of Scripture.",
    strongs: "H559",
    occurrences: 5300,
    verse: {
      ref: "Genesis 1:3",
      he: "וַיֹּאמֶר אֱלֹהִים",
      en: "And God said…",
    },
  },
  {
    hebrew: "שָׁמַע",
    translit: "šāmaʿ",
    pron: "sha-MAH",
    pos: "verb",
    gloss: "to hear, obey",
    meaning:
      "To hear, listen, and so to heed or obey — hearing that leads to action.",
    strongs: "H8085",
    occurrences: 1165,
    verse: {
      ref: "Deuteronomy 6:4",
      he: "שְׁמַע יִשְׂרָאֵל",
      en: "Hear, O Israel…",
    },
  },
  {
    hebrew: "בָּרַךְ",
    translit: "bāraḵ",
    pron: "ba-RAKH",
    pos: "verb",
    gloss: "to bless, kneel",
    meaning:
      "To bless — to bestow favor or invoke good; from a root tied to kneeling in homage.",
    strongs: "H1288",
    occurrences: 327,
    verse: {
      ref: "Numbers 6:24",
      he: "יְבָרֶכְךָ יְהוָה",
      en: "The LORD bless you…",
    },
  },
  {
    hebrew: "יָדַע",
    translit: "yāḏaʿ",
    pron: "ya-DAH",
    pos: "verb",
    gloss: "to know",
    meaning:
      "To know — by experience and relationship, not just intellect; intimate, personal knowing.",
    strongs: "H3045",
    occurrences: 947,
    verse: {
      ref: "Psalm 46:10",
      he: "דְּעוּ כִּי־אָנֹכִי אֱלֹהִים",
      en: "…know that I am God.",
    },
  },
  {
    hebrew: "עָשָׂה",
    translit: "ʿāśāh",
    pron: "ah-SAH",
    pos: "verb",
    gloss: "to do, make",
    meaning:
      "To do, make, or accomplish — a broad verb of action and creation.",
    strongs: "H6213",
    occurrences: 2630,
    verse: {
      ref: "Genesis 1:7",
      he: "וַיַּעַשׂ אֱלֹהִים",
      en: "And God made…",
    },
  },
  {
    hebrew: "נָתַן",
    translit: "nāṯan",
    pron: "na-TAHN",
    pos: "verb",
    gloss: "to give, set, place",
    meaning:
      "To give, grant, put, or set — one of the most common verbs in the Hebrew Bible.",
    strongs: "H5414",
    occurrences: 2010,
    verse: {
      ref: "Psalm 29:11",
      he: "יְהוָה עֹז לְעַמּוֹ יִתֵּן",
      en: "The LORD gives strength to his people.",
    },
  },
  {
    hebrew: "רָאָה",
    translit: "rāʾāh",
    pron: "ra-AH",
    pos: "verb",
    gloss: "to see, perceive",
    meaning:
      "To see, look, or perceive — physical sight and insight, including prophetic vision.",
    strongs: "H7200",
    occurrences: 1300,
    verse: {
      ref: "Genesis 1:4",
      he: "וַיַּרְא אֱלֹהִים כִּי־טוֹב",
      en: "And God saw that it was good.",
    },
  },
  {
    hebrew: "הָלַךְ",
    translit: "hālaḵ",
    pron: "ha-LAKH",
    pos: "verb",
    gloss: "to walk, go",
    meaning:
      "To walk or go — and figuratively to live or conduct oneself (“walk with God”).",
    strongs: "H1980",
    occurrences: 1550,
    verse: {
      ref: "Micah 6:8",
      he: "וְהַצְנֵעַ לֶכֶת עִם־אֱלֹהֶיךָ",
      en: "…and to walk humbly with your God.",
    },
  },
  {
    hebrew: "גּוֹי",
    translit: "gôy",
    pron: "GOY",
    pos: "noun (m.)",
    gloss: "nation",
    meaning:
      "A nation or people — often the nations beyond Israel, the Gentiles.",
    strongs: "H1471",
    occurrences: 561,
    verse: {
      ref: "Genesis 12:2",
      he: "וְאֶעֶשְׂךָ לְגוֹי גָּדוֹל",
      en: "…and I will make you a great nation.",
    },
  },
];
